services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/myapp?authSource=admin
      - FLASK_DEBUG=1

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
