apiVersion: apps/v1
kind: Deployment
metadata:
  name: conference-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conference-app
  template:
    metadata:
      labels:
        app: conference-app
    spec:
      containers:
      - name: app
        image: a666vg/conference-app:latest  
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://pypypy/conference_db"  
        