apiVersion: v1
kind: Service
metadata:
  name: conference-app-service
  namespace: test
spec:
  selector:
    app: conference-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP  