name: Build, Push and Deploy

on:
  push:
    branches: [dev, prod]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Dev
      if: github.ref == 'refs/heads/dev'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: a666vg/conference-app:dev

    - name: Build and Push Prod
      if: github.ref == 'refs/heads/prod'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: a666vg/conference-app:prod

    - name: Setup Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.30.2'

    - name: Deploy to Kubernetes Dev
      if: github.ref == 'refs/heads/dev'
      run: |
        kubectl config set-cluster k8s --server=${{ secrets.K8S_CLUSTER_URL }} --insecure-skip-tls-verify=true
        kubectl config set-credentials github --token=${{ secrets.K8S_CLUSTER_TOKEN }}
        kubectl config set-context k8s --cluster=k8s --user=github
        kubectl config use-context k8s
        
        #kubectl set image deployment/conference-app conference-app=a666vg/conference-app:dev -n dev
        #kubectl rollout restart deployment/conference-app -n dev
        POD_NAME=$(kubectl get pods -n dev -o jsonpath='{.items[0].metadata.name}')
        kubectl exec -n dev $POD_NAME -- cat /app/kubernetes/dev/deployment.yaml | kubectl apply -f -
        kubectl rollout status deployment/conference-app -n dev
        kubectl rollout restart deployment/conference-app -n dev
        #nohup kubectl port-forward -n dev service/conference-app-service 8080:80 --address 0.0.0.0 &


    - name: Deploy to Kubernetes Prod
      if: github.ref == 'refs/heads/prod'
      run: |
        kubectl config set-cluster k8s --server=${{ secrets.K8S_CLUSTER_URL }} --insecure-skip-tls-verify=true
        kubectl config set-credentials github --token=${{ secrets.K8S_CLUSTER_TOKEN }}
        kubectl config set-context k8s --cluster=k8s --user=github
        kubectl config use-context k8s
        
        POD_NAME=$(kubectl get pods -n prod -o jsonpath='{.items[0].metadata.name}')
        kubectl exec -n prod $POD_NAME -- cat /app/kubernetes/prod/deployment.yaml | kubectl apply -f -
        kubectl rollout status deployment/conference-app -n prod
        
